export const departments = [
  { id: "dept-hr", name: "HR", code: "HR" },
  { id: "dept-eng", name: "Engineering", code: "ENG" },
  { id: "dept-fin", name: "Finance", code: "FIN" },
  { id: "dept-ops", name: "Operations", code: "OPS" },
  { id: "dept-sal", name: "Sales", code: "SAL" },
  { id: "dept-mkt", name: "Marketing", code: "MKT" },
  { id: "dept-it", name: "IT", code: "IT" }
];

export const designations = [
  { id: "desg-hrm", name: "HR Manager" },
  { id: "desg-hr", name: "HR Executive" },
  { id: "desg-rec", name: "Recruiter" },
  { id: "desg-fe", name: "Frontend Engineer" },
  { id: "desg-be", name: "Backend Engineer" },
  { id: "desg-fs", name: "Full Stack Engineer" },
  { id: "desg-qa", name: "QA Analyst" },
  { id: "desg-qa-lead", name: "QA Lead" },
  { id: "desg-fin", name: "Payroll Analyst" },
  { id: "desg-sal-mgr", name: "Sales Manager" },
  { id: "desg-sales", name: "Account Executive" },
  { id: "desg-devops", name: "DevOps Engineer" },
  { id: "desg-design", name: "Product Designer" },
  { id: "desg-support", name: "Support Associate" },
  { id: "desg-compliance", name: "Compliance Officer" },
  { id: "desg-content", name: "Content Specialist" },
  { id: "desg-it", name: "IT Administrator" }
];

export const workLocations = [
  { id: "loc-blr", name: "Bengaluru HQ", city: "Bengaluru", country: "India" },
  { id: "loc-mum", name: "Mumbai", city: "Mumbai", country: "India" },
  { id: "loc-del", name: "Delhi", city: "Delhi", country: "India" }
];

export const employees = [
  {
    employeeCode: "HRM0001",
    userId: "demo-user",
    firstName: "Aarav",
    lastName: "Sharma",
    personalEmail: "hr.manager@qode27.com",
    phone: "9000000001",
    joiningDate: "2024-04-01",
    employmentType: "FULL_TIME",
    department: "HR",
    designation: "HR Manager",
    managerCode: "",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 125000,
    status: "ACTIVE",
    skills: ["People Ops", "Policy", "Compliance", "HRMS"]
  },
  {
    employeeCode: "ENG0001",
    firstName: "Diya",
    lastName: "Patel",
    personalEmail: "diya.patel@qode27.com",
    phone: "9000000002",
    joiningDate: "2024-06-10",
    employmentType: "FULL_TIME",
    department: "Engineering",
    designation: "Frontend Engineer",
    managerCode: "HRM0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 115000,
    status: "ACTIVE",
    skills: ["React", "Next.js", "TypeScript", "Design Systems"]
  },
  {
    employeeCode: "ENG0002",
    firstName: "Kabir",
    lastName: "Singh",
    personalEmail: "kabir.singh@qode27.com",
    phone: "9000000003",
    joiningDate: "2024-07-18",
    employmentType: "FULL_TIME",
    department: "Engineering",
    designation: "Backend Engineer",
    managerCode: "ENG0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 118000,
    status: "ACTIVE",
    skills: ["Node.js", "Prisma", "PostgreSQL", "APIs"]
  },
  {
    employeeCode: "ENG0003",
    firstName: "Meera",
    lastName: "Joshi",
    personalEmail: "meera.joshi@qode27.com",
    phone: "9000000004",
    joiningDate: "2024-08-05",
    employmentType: "FULL_TIME",
    department: "Engineering",
    designation: "Full Stack Engineer",
    managerCode: "ENG0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 122500,
    status: "ACTIVE",
    skills: ["React", "Node.js", "Testing", "DevEx"]
  },
  {
    employeeCode: "OPS0001",
    firstName: "Ishaan",
    lastName: "Reddy",
    personalEmail: "ishaan.reddy@qode27.com",
    phone: "9000000005",
    joiningDate: "2024-05-20",
    employmentType: "FULL_TIME",
    department: "Operations",
    designation: "QA Lead",
    managerCode: "HRM0001",
    workLocation: "Delhi",
    salaryMonthly: 110000,
    status: "ACTIVE",
    skills: ["QA", "Automation", "CI/CD", "Release Management"]
  },
  {
    employeeCode: "OPS0002",
    firstName: "Anaya",
    lastName: "Khan",
    personalEmail: "anaya.khan@qode27.com",
    phone: "9000000006",
    joiningDate: "2024-09-02",
    employmentType: "CONTRACT",
    department: "Operations",
    designation: "QA Analyst",
    managerCode: "OPS0001",
    workLocation: "Delhi",
    salaryMonthly: 86000,
    status: "ACTIVE",
    skills: ["Manual Testing", "SQL", "API Validation"]
  },
  {
    employeeCode: "HR0002",
    firstName: "Rohan",
    lastName: "Patel",
    personalEmail: "rohan.patel@qode27.com",
    phone: "9000000007",
    joiningDate: "2024-04-14",
    employmentType: "FULL_TIME",
    department: "HR",
    designation: "Recruiter",
    managerCode: "HRM0001",
    workLocation: "Mumbai",
    salaryMonthly: 90000,
    status: "ACTIVE",
    skills: ["Hiring", "ATS", "Candidate Screening"]
  },
  {
    employeeCode: "HR0003",
    firstName: "Sana",
    lastName: "Nair",
    personalEmail: "sana.nair@qode27.com",
    phone: "9000000008",
    joiningDate: "2024-10-11",
    employmentType: "FULL_TIME",
    department: "HR",
    designation: "HR Executive",
    managerCode: "HRM0001",
    workLocation: "Mumbai",
    salaryMonthly: 78000,
    status: "ACTIVE",
    skills: ["Onboarding", "HR Ops", "Employee Relations"]
  },
  {
    employeeCode: "FIN0001",
    firstName: "Vivaan",
    lastName: "Gupta",
    personalEmail: "vivaan.gupta@qode27.com",
    phone: "9000000009",
    joiningDate: "2024-03-21",
    employmentType: "FULL_TIME",
    department: "Finance",
    designation: "Payroll Analyst",
    managerCode: "HRM0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 95000,
    status: "ACTIVE",
    skills: ["Payroll", "Compliance", "Excel", "Statutory Filings"]
  },
  {
    employeeCode: "FIN0002",
    firstName: "Aanya",
    lastName: "Verma",
    personalEmail: "aanya.verma@qode27.com",
    phone: "9000000010",
    joiningDate: "2024-11-07",
    employmentType: "FULL_TIME",
    department: "Finance",
    designation: "Finance Associate",
    managerCode: "FIN0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 84000,
    status: "ACTIVE",
    skills: ["Accounts", "Payroll Support", "Reporting"]
  },
  {
    employeeCode: "SAL0001",
    firstName: "Arjun",
    lastName: "Das",
    personalEmail: "arjun.das@qode27.com",
    phone: "9000000011",
    joiningDate: "2024-02-19",
    employmentType: "FULL_TIME",
    department: "Sales",
    designation: "Sales Manager",
    managerCode: "HRM0001",
    workLocation: "Mumbai",
    salaryMonthly: 130000,
    status: "ACTIVE",
    skills: ["Negotiation", "Forecasting", "Client Relations"]
  },
  {
    employeeCode: "SAL0002",
    firstName: "Priya",
    lastName: "Iyer",
    personalEmail: "priya.iyer@qode27.com",
    phone: "9000000012",
    joiningDate: "2024-12-01",
    employmentType: "FULL_TIME",
    department: "Sales",
    designation: "Account Executive",
    managerCode: "SAL0001",
    workLocation: "Mumbai",
    salaryMonthly: 98000,
    status: "ACTIVE",
    skills: ["Pipeline Management", "CRM", "Client Communication"]
  },
  {
    employeeCode: "IT0001",
    firstName: "Karan",
    lastName: "Mehta",
    personalEmail: "karan.mehta@qode27.com",
    phone: "9000000013",
    joiningDate: "2024-06-22",
    employmentType: "FULL_TIME",
    department: "IT",
    designation: "IT Administrator",
    managerCode: "HRM0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 105000,
    status: "ACTIVE",
    skills: ["Support", "Identity", "Devices", "Networking"]
  },
  {
    employeeCode: "DES0001",
    firstName: "Ira",
    lastName: "Sharma",
    personalEmail: "ira.sharma@qode27.com",
    phone: "9000000014",
    joiningDate: "2024-07-30",
    employmentType: "PART_TIME",
    department: "Marketing",
    designation: "Product Designer",
    managerCode: "HRM0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 90000,
    status: "ACTIVE",
    skills: ["Figma", "UX", "Prototyping", "Design Tokens"]
  },
  {
    employeeCode: "SUP0001",
    firstName: "Rahul",
    lastName: "Verma",
    personalEmail: "rahul.verma@qode27.com",
    phone: "9000000015",
    joiningDate: "2024-05-13",
    employmentType: "FULL_TIME",
    department: "Operations",
    designation: "Support Lead",
    managerCode: "HRM0001",
    workLocation: "Delhi",
    salaryMonthly: 87000,
    status: "ACTIVE",
    skills: ["Support Ops", "Escalation", "Documentation"]
  },
  {
    employeeCode: "SUP0002",
    firstName: "Nisha",
    lastName: "Reddy",
    personalEmail: "nisha.reddy@qode27.com",
    phone: "9000000016",
    joiningDate: "2024-08-26",
    employmentType: "FULL_TIME",
    department: "Operations",
    designation: "Support Associate",
    managerCode: "SUP0001",
    workLocation: "Delhi",
    salaryMonthly: 68000,
    status: "ACTIVE",
    skills: ["Customer Support", "Troubleshooting", "Communication"]
  },
  {
    employeeCode: "ENG0004",
    firstName: "Dev",
    lastName: "Joshi",
    personalEmail: "dev.joshi@qode27.com",
    phone: "9000000017",
    joiningDate: "2024-09-18",
    employmentType: "FULL_TIME",
    department: "Engineering",
    designation: "DevOps Engineer",
    managerCode: "ENG0001",
    workLocation: "Bengaluru HQ",
    salaryMonthly: 124000,
    status: "ACTIVE",
    skills: ["AWS", "CI/CD", "Containers", "Observability"]
  },
  {
    employeeCode: "MKT0001",
    firstName: "Riya",
    lastName: "Khan",
    personalEmail: "riya.khan@qode27.com",
    phone: "9000000018",
    joiningDate: "2024-03-10",
    employmentType: "FULL_TIME",
    department: "Marketing",
    designation: "Marketing Manager",
    managerCode: "HRM0001",
    workLocation: "Mumbai",
    salaryMonthly: 120000,
    status: "ACTIVE",
    skills: ["Campaigns", "Brand", "Analytics"]
  },
  {
    employeeCode: "MKT0002",
    firstName: "Om",
    lastName: "Patel",
    personalEmail: "om.patel@qode27.com",
    phone: "9000000019",
    joiningDate: "2024-10-24",
    employmentType: "FULL_TIME",
    department: "Marketing",
    designation: "Content Specialist",
    managerCode: "MKT0001",
    workLocation: "Mumbai",
    salaryMonthly: 76000,
    status: "ACTIVE",
    skills: ["Copywriting", "Social", "SEO"]
  },
  {
    employeeCode: "LEG0001",
    firstName: "Pooja",
    lastName: "Singh",
    personalEmail: "pooja.singh@qode27.com",
    phone: "9000000020",
    joiningDate: "2024-11-15",
    employmentType: "FULL_TIME",
    department: "Operations",
    designation: "Compliance Officer",
    managerCode: "HRM0001",
    workLocation: "Delhi",
    salaryMonthly: 108000,
    status: "LOCKED",
    skills: ["Compliance", "Audits", "Policy"]
  }
];
